### ISSUE TITLE
runtime error chapter 7

### ISSUE THREAD

**Issue by KewTeacher** [Taneil-Kew/Hw#3]
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\GitHub\taneil\Hw\Chapter 7", line 87, in <module>
    test_suite()
  File "C:\Users\Admin\Documents\GitHub\taneil\Hw\Chapter 7", line 11, in test_suite
    test(sum_to_even(mylist)==10)
NameError: name 'sum_to_even' is not defined

HintL: your function is defined as "sumtoeven" but you're calling  'sum_to_even'

**Comment by KewTeacher** [comment]
Also name your file with ".py" at the end
